Adding occupied spot number attribute
smart-data-models/dataModel.Parking pull request #17
Opened 2020-12-15 11:07 UTC by jpnbastos

PR to close issue #15

2020-12-16 08:46 UTC, albertoabellagarcia commented
Thank you very much for your PR. I am afraid that you have worked very hard in points that are not 'useful'. 
The only documents that you need to contributed to, are the examples and the schema.json. (And eventually the notes.yaml if you want to customize the spec, and of course the contributors.yaml at subject level)
 The rest of the documentation is generated automatically from them. 
So from your PR the only thing to be reviewed is the schema.json, and on the other hand you did not update the examples which are relevant this case.
See the contributor manual https://docs.google.com/presentation/d/e/2PACX-1vTs-Ng5dIAwkg91oTTUdt8ua7woBXhPnwavZ0FxgR8BsAI_Ek3C5q97Nd94HS8KhP-r_quD4H0fgyt3/pub?start=false&loop=false&delayms=3000#slide=id.p1 for further insights 
Actions on your part:
1) Please extend your PR to include the examples
2) 'drop' the modifications in the spec.md, spec-ES.md, model.yaml, etc  because they will be overwritten once approved the schema.json and the examples modifications. 
if you have any other doubt please check the manual or just drop me an email alberto.abella@fiware.org

2020-12-16 10:55 UTC, jpnbastos commented
Oh I see, I indeed did not consider that possibility. I will do so :) 

Thank you for the info!

2020-12-16 10:56 UTC, jpnbastos commented
Btw, the contributor manual. I was looking for such a document before but I could not. Of course it can just mean that I did not look well or it missed me, but I would suggest adding it to the README.md of this project and others. :)

2020-12-17 11:15 UTC, jpnbastos commented
It is done. Let me know if anything else is needed 👍

2020-12-21 01:35 UTC, albertoabellagarcia commented on OnStreetParking/examples/example-normalized-ld.jsonld.csv
> +"id_", "type_", "modifiedAt_", "category__type_", "category__value__0_", "category__value__1_", "category__value__2_", "permitActiveHours__type_", "permitActiveHours__value__blueZonePermit_", "requir
this file is generated automatically so it is not necessary (either convenient to be in the PR)

2020-12-21 01:35 UTC, albertoabellagarcia commented on OnStreetParking/examples/example-normalized.json.csv
> +"id_", "type_", "category__value__0_", "category__value__1_", "category__value__2_", "permitActiveHours__value__blueZonePermit_", "requiredPermit__value__0_", "requiredPermit__value__1_", "allowedVeh
this file is generated automatically so it is not necessary (either convenient to be in the PR)

2020-12-21 01:36 UTC, albertoabellagarcia commented on OnStreetParking/examples/example.json.csv
> +"id_", "type_", "category__0_", "category__1_", "category__2_", "allowedVehicleType_", "chargeType__0_", "requiredPermit__0_", "requiredPermit__1_", "permitActiveHours__blueZonePermit_", "maximumAllo
this file is generated automatically so it is not necessary (either convenient to be in the PR)

2020-12-21 01:36 UTC, albertoabellagarcia requested changes
It's ok but you have to remove the .csv files from the PR

2020-12-22 09:52 UTC, jpnbastos commented
they are now removed. thanks!

2021-01-11 16:32 UTC, jpnbastos commented
Hi Alberto, 

Is more work needed on this PR?

2021-01-12 01:28 UTC, albertoabellagarcia commented
All files are right but the schema.json. Sorry to say that you did not remember to include the description in the change in the json schema for the data model. Please see the actual version of [schema.json](https://github.com/smart-data-models/dataModel.Parking/blob/master/OffStreetParking/schema.json) and the [contribution manual](https://bit.ly_contriubution_manual), page 9. 
Any doubt, please let me know.

2021-01-12 15:04 UTC, jpnbastos commented
No problem, I have now added the description of the attribute, but as well update the schema. I noticed that it was not the latest schema version. Please have a look.

2021-01-12 15:18 UTC, merged

2021-01-12 15:18 UTC, albertoabellagarcia commented
nice, thanks for your contribution